name: Deployment workflow
on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Deploys from the Github-Deployer subfolder since index.html lives there, not at the repo root.
          path: "./Github-Deployer"
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4